### ISSUE TITLE
App is not working

### ISSUE THREAD

**Issue by enderahmetyurt** [jasonswett/instant_rails#3]
I did the instructions but localhost:3000 not responding. you can see the screenshots. 

![Screen Shot 2021-08-24 at 16 51 00](https://user-images.githubusercontent.com/447588/130628870-965e9306-3848-4ca7-9a47-af3d6f005d58.png)

![Screen Shot 2021-08-24 at 16 51 07](https://user-images.githubusercontent.com/447588/130628879-81f53050-9141-4418-b874-9a51bcc6eb0d.png)

do you have any idea?

Cheers.

**Comment by jasonswett** [comment]
Try `localhost:3001` instead - I believe port 3000 is getting forwarded to port 3001.

https://github.com/jasonswett/instant_rails/blob/master/docker-compose.yml#L67
