### ISSUE TITLE
Setup fails when Cryptography attempts to run Rust

### ISSUE THREAD

**Issue by RieMars** [jasonswett/instant_rails#4]
Just tried following your setup instructions but had the following result:

#6 22.27   copying src/cryptography/py.typed -> build/lib.linux-x86_64-3.8/cryptography
#6 22.27   creating build/lib.linux-x86_64-3.8/cryptography/hazmat/bindings/_rust
#6 22.27   copying src/cryptography/hazmat/bindings/_rust/__init__.pyi -> build/lib.linux-x86_64-3.8/cryptography/hazmat/bindings/_rust
#6 22.27   copying src/cryptography/hazmat/bindings/_rust/asn1.pyi -> build/lib.linux-x86_64-3.8/cryptography/hazmat/bindings/_rust
#6 22.27   copying src/cryptography/hazmat/bindings/_rust/ocsp.pyi -> build/lib.linux-x86_64-3.8/cryptography/hazmat/bindings/_rust
#6 22.27   copying src/cryptography/hazmat/bindings/_rust/x509.pyi -> build/lib.linux-x86_64-3.8/cryptography/hazmat/bindings/_rust
#6 22.27   running build_ext
#6 22.27   running build_rust
#6 22.27   
#6 22.27       =============================DEBUG ASSISTANCE=============================
#6 22.27       If you are seeing a compilation error please try the following steps to
#6 22.27       successfully install cryptography:
#6 22.27       1) Upgrade to the latest pip and try again. This will fix errors for most
#6 22.27          users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
#6 22.27       2) Read https://cryptography.io/en/latest/installation/ for specific
#6 22.27          instructions for your platform.
#6 22.27       3) Check our frequently asked questions for more information:
#6 22.27          https://cryptography.io/en/latest/faq/
#6 22.27       4) Ensure you have a recent Rust toolchain installed:
#6 22.27          https://cryptography.io/en/latest/installation/#rust
#6 22.27   
#6 22.27       Python: 3.8.10
#6 22.27       platform: Linux-5.10.76-linuxkit-x86_64-with
#6 22.27       pip: n/a
#6 22.27       setuptools: 60.9.3
#6 22.27       setuptools_rust: 1.1.2
#6 22.27       =============================DEBUG ASSISTANCE=============================
#6 22.27   
#6 22.27   error: can't find Rust compiler
#6 22.27   
#6 22.27   If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
#6 22.27   
#6 22.27   To update pip, run:
#6 22.27   
#6 22.27       pip install --upgrade pip
#6 22.27   
#6 22.27   and then retry package installation.
#6 22.27   
#6 22.27   If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
#6 22.27   
#6 22.27   This package requires Rust >=1.41.0.
#6 22.27   ----------------------------------------
#6 22.27   ERROR: Failed building wheel for cryptography
#6 22.27 Failed to build cryptography
#6 22.27 ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly

**Comment by jasonswett** [comment]
Sorry I never got around to addressing this. At this point Instant Rails works fundamentally differently so I assume this issue doesn't apply anymore anyway.
